---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - id: fmt
      - id: clippy
    repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.30.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        stages:
          - commit
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.0
    hooks:
      - id: toml-sort-fix
